//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bnebookstore_dbfirstmvcproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderNo { get; set; }
        public Nullable<System.DateTime> DateofOrder { get; set; }
        public string Basket { get; set; }
        public Nullable<decimal> TotalPayment { get; set; }
        public string Adress { get; set; }
        public Nullable<int> CustomerNo { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
