//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bnebookstore_dbfirstmvcproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int StoreNo { get; set; }
        public Nullable<bool> Website { get; set; }
        public Nullable<int> NumberofEmployee { get; set; }
        public string NameofStore { get; set; }
        public string City { get; set; }
        public Nullable<int> EmployeeNo { get; set; }
        public Nullable<int> BookNo { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
